### ISSUE TITLE
Publisher.ack_cb: any use case?

### ISSUE THREAD

**Issue by oblalex** [mackeyja92/asyncio-nats-streaming#1]
Hi,

Thanks for your library!

In your examples you are just printing `ack`s. Are there any use cases where handling that can be useful? I'm new to NATS and NATS streaming, so maybe this is covered somewhere, but I'll be glad if you can provide some details in relation to your library.

Thanks!

**Comment by mackeyja92** [comment]
@oblalex No there is no particular use case that I know of. It may be nice to store them if you need them in your application. But in this case it was just showing that the server received the messages.

**Comment by oblalex** [comment]
Got it, thank you!
