### ISSUE TITLE
Potential bug when using external NATS client

### ISSUE THREAD

**Issue by oblalex** [mackeyja92/asyncio-nats-streaming#2]
Hi,

I was examining `StreamClient.connect()` recently and it seems to have a bug when passing external NATS client to it. There is a check for it, it is never used and not assigned to `self`. However, code after the check accesses the client as `self.nc`. 

See the lines: https://github.com/mackeyja92/asyncio-nats-streaming/blob/a81f5480df818bf3bd0f91b8441e0bab52e3191c/nats_stream/aio/client.py#L90-L91

Is that ok? `nc_owned` is changed, but `nc` is never assigned.

Thanks

**Comment by mackeyja92** [comment]
You're right, it wasn't being used. The fix is easy and I will get it out today.

**Comment by mackeyja92** [comment]
I have pushed v0.2.1 to PyPI and it should be fixed. Thanks for reporting.
